name: Publish release version

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install jdk
        uses: actions/setup-java@v1
        with:
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: set version from tag
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            versions:set \
            -DnewVersion=${GITHUB_REF##*/v} \
            versions:commit

      - name: deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
        run: |
          mvn \
            --batch-mode \
            --no-transfer-progress \
            clean deploy -P deploy-to-sonatype

      - name: Create github release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          RELEASE_NAME_PREFIX: "Release: "
        with:
          args: |
            ./target/asciidoctor-office-extension-*.jar

  announcement:
    name: "Send announcements"
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Announcement
        uses: yuzutech/zulip-send-message-action@v0.1.0
        with:
          username: ${{ secrets.ZULIP_USERNAME }}
          api-key: ${{ secrets.ZULIP_API_KEY }}
          organization-url: 'https://asciidoctor.zulipchat.com'
          to: '279652'
          type: 'stream'
          topic: 'contrib releases'
          content: |
            asciidoctorj-office-extension ${{ env.RELEASE_VERSION }} is out!
            https://github.com/uniqueck/asciidoctorj-office-extension/releases/tag/${{ env.RELEASE_VERSION }}
